### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by Haimu-ad** [DrinkWaterUWP/DrinkWater#5]
Hi, I would like you to add a new feature where we can set multiple schedules, for 1st schedule(eg:- 3 pm-10 pm) I get a notification to drink water and for another schedule(eg:- 3 pm-10 pm (same time) or different time(5 pm-11 pm) we get notification regarding taking a snack or a walk, etc.

Hope you will work on my suggestion.
Thanks:)

**Comment by DrinkWaterUWP** [comment]
Hi @Haimu-ad, we will not implement this feature in any near future.

Thank you for your feature request.
