### ISSUE TITLE
App stops working.

### ISSUE THREAD

**Issue by Haimu-ad** [DrinkWaterUWP/DrinkWater#6]
The app was running smoothly for some months after that, it stopped working suddenly. I have set the time to receive notification as 16:00-23:00 and the timer shows as started but the timer is not running it's stuck. I have to click on stop timer and then again begin timer then only it starts working.

**Comment by DrinkWaterUWP** [comment]
Thank you for your bug report.

The new version is available now.

You can update the app for the fix.

Please let us know if the issue happens again.
